[package]
name = "mangokv"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.1.4"
home = "0.5.4"
sled = "0.34.7"
clap-verbosity-flag = "2.0.0"
env_logger = "0.10.0"
log = "0.4.17"
just_macros = "0.1.2"
termcolor = "1.2.0"
anyhow = "1.0.68"
colored = "2.0.0"
prettytable = "0.10.0"
